config/routes.rb
Rails.application.routes.draw do
  root to: 'shortcuts#new'

  get '/:shortcut_key' => 'shortcuts#show', as: :shortcut, shortcut_key: /[[:alnum:]]{7}/

  resources :shortcuts, only: %i(create)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shortcut.rb
class Shortcut < ApplicationRecord
  validates :url, :key, presence: true
  validates :url, format: { with: URI.regexp(['http', 'https']) }
  validates :key, uniqueness: true, length: { is: 7 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/shortcuts_controller.rb
class ShortcutsController < ApplicationController
  def new
    @shortcut = Shortcut.new
  end

  def create
    @shortcut = Shortcuts::Create.call(shortcut_params)

    if @shortcut.persisted?
      render status: :created
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    shortcut = Shortcut.find_by!(key: params[:shortcut_key])

    redirect_to shortcut.url, status: :moved_permanently

    expires_in(365.days)
  end

  private

  def shortcut_params
    params
      .require(:shortcut)
      .permit(:url)
      .to_h.symbolize_keys
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chikito</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shortcuts/create.html.erb
<p><b>Original: </b><%= @shortcut.url %></p>
<p><b>Shortcut: </b><%= link_to shortcut_url(@shortcut.key), shortcut_path(@shortcut.key), target: :blank %></p>

<%= link_to 'New Shortcut', :root %>

app/views/shortcuts/new.html.erb
<h1>Shortcuts</h1>
<p>A simple URL shortener</p>
<%= form_with model: @shortcut do |form| %>
  <div>
    <%= form.url_field :url, placeholder: 'Url' %><br/>
    <% @shortcut.errors.full_messages_for(:url).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.submit "Shorten" %>
  </div>
<% end %>